"""
make_examples.py - run every program on sample boards and write Examples.txt.

Usage: python make_examples.py
"""

import os
import subprocess
import sys
import tempfile

from morris_core import *  # noqa: F403

HERE = os.path.dirname(os.path.abspath(__file__))

OPENING_BOARDS = [
    ("an empty board", "xxxxxxxxxxxxxxxxxxxxxxx", 3),
    ("an early opening position", "xxxWxBxxxBxxxxxxxWxxxxx", 3),
]
GAME_BOARDS = [
    ("first board pictured in the Morris handout", "xxxxxBxWWWWWBBBBxxxxxxx", 3),
    ("second board pictured in the Morris handout", "WxWWxWWWWWBBBBBBBBxxxxx", 2),
]


def run(program, board, depth):
    with tempfile.TemporaryDirectory() as tmp:
        inp, out = os.path.join(tmp, "board1.txt"), os.path.join(tmp, "board2.txt")
        write_board(inp, board)
        proc = subprocess.run(
            [sys.executable, os.path.join(HERE, program), inp, out, str(depth)],
            capture_output=True, text=True, check=True,
        )
        return proc.stdout.strip()


def evaluated(output):
    for line in output.splitlines():
        if line.startswith("Positions evaluated"):
            return int(line.split(":")[1])
    raise ValueError(output)


def section(lines, title):
    lines += ["", "=" * 72, title, "=" * 72]


def example(lines, program, board, depth, note):
    output = run(program, board, depth)
    lines += [
        "",
        f"python {program} board1.txt board2.txt {depth}",
        f"  board1.txt: {board}   ({note})",
        "",
        render_board(board),
        "",
        output,
    ]
    return output


def main():
    lines = [
        "Examples.txt - sample runs of every program (generated by make_examples.py)",
        "",
        "Boards are 23-character strings, index -> location:",
        "  " + " ".join(f"{i:>2}" for i in range(BOARD_SIZE)),
        "  " + " ".join(f"{n:>2}" for n in LOCATION_NAMES),
        "",
        "Black programs use color swapping, so their MINIMAX estimate is from",
        "Black's point of view (positive = good for Black).",
    ]

    comparisons = []
    for phase, boards, mm, ab in (
        ("OPENING", OPENING_BOARDS, "MiniMaxOpening.py", "ABOpening.py"),
        ("MIDGAME/ENDGAME", GAME_BOARDS, "MiniMaxGame.py", "ABGame.py"),
    ):
        section(lines, f"Part I and II, {phase}: MINIMAX vs ALPHA-BETA")
        for note, board, depth in boards:
            out_mm = example(lines, mm, board, depth, note)
            out_ab = example(lines, ab, board, depth, note)
            same = out_mm.splitlines()[0] == out_ab.splitlines()[0] and \
                out_mm.splitlines()[2] == out_ab.splitlines()[2]
            comparisons.append((mm, ab, board, depth, evaluated(out_mm), evaluated(out_ab), same))

    section(lines, "Summary: positions evaluated, MINIMAX vs ALPHA-BETA")
    lines.append("")
    for mm, ab, board, depth, n_mm, n_ab, same in comparisons:
        lines.append(f"{board} depth {depth}: {mm} {n_mm:>7}   {ab} {n_ab:>7}   "
                     f"same move and estimate: {'yes' if same else 'NO'}")

    section(lines, "Part III: playing Black")
    example(lines, "MiniMaxOpeningBlack.py", OPENING_BOARDS[1][1], 3, "Black to move")
    example(lines, "MiniMaxGameBlack.py", GAME_BOARDS[0][1], 3, "Black to move")
    example(lines, "MiniMaxGameBlack.py", GAME_BOARDS[1][1], 2, "Black to move")

    section(lines, "Part IV: improved static estimation (see MyStaticEstimation.txt)")
    example(lines, "MiniMaxOpeningImproved.py", OPENING_BOARDS[1][1], 3, "same as above")
    example(lines, "MiniMaxGameImproved.py", GAME_BOARDS[0][1], 3, "same as above")
    example(lines, "MiniMaxGameImproved.py", GAME_BOARDS[1][1], 2, "same as above")

    with open(os.path.join(HERE, "Examples.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote Examples.txt")


if __name__ == "__main__":
    main()
