/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as ClubRouteImport } from './routes/club'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as GiftCardsRouteImport } from './routes/gift-cards'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as NewsRouteImport } from './routes/news'
import { Route as SaucesRouteImport } from './routes/sauces'
import { Route as StoryRouteImport } from './routes/story'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardsRoute = GiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const SaucesRoute = SaucesRouteImport.update({
  id: '/sauces',
  path: '/sauces',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catering': typeof CateringRoute
  '/club': typeof ClubRoute
  '/feedback': typeof FeedbackRoute
  '/gift-cards': typeof GiftCardsRoute
  '/menu': typeof MenuRoute
  '/news': typeof NewsRoute
  '/sauces': typeof SaucesRoute
  '/story': typeof StoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catering': typeof CateringRoute
  '/club': typeof ClubRoute
  '/feedback': typeof FeedbackRoute
  '/gift-cards': typeof GiftCardsRoute
  '/menu': typeof MenuRoute
  '/news': typeof NewsRoute
  '/sauces': typeof SaucesRoute
  '/story': typeof StoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catering': typeof CateringRoute
  '/club': typeof ClubRoute
  '/feedback': typeof FeedbackRoute
  '/gift-cards': typeof GiftCardsRoute
  '/menu': typeof MenuRoute
  '/news': typeof NewsRoute
  '/sauces': typeof SaucesRoute
  '/story': typeof StoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catering'
    | '/club'
    | '/feedback'
    | '/gift-cards'
    | '/menu'
    | '/news'
    | '/sauces'
    | '/story'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catering'
    | '/club'
    | '/feedback'
    | '/gift-cards'
    | '/menu'
    | '/news'
    | '/sauces'
    | '/story'
  id:
    | '__root__'
    | '/'
    | '/catering'
    | '/club'
    | '/feedback'
    | '/gift-cards'
    | '/menu'
    | '/news'
    | '/sauces'
    | '/story'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CateringRoute: typeof CateringRoute
  ClubRoute: typeof ClubRoute
  FeedbackRoute: typeof FeedbackRoute
  GiftCardsRoute: typeof GiftCardsRoute
  MenuRoute: typeof MenuRoute
  NewsRoute: typeof NewsRoute
  SaucesRoute: typeof SaucesRoute
  StoryRoute: typeof StoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-cards': {
      id: '/gift-cards'
      path: '/gift-cards'
      fullPath: '/gift-cards'
      preLoaderRoute: typeof GiftCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sauces': {
      id: '/sauces'
      path: '/sauces'
      fullPath: '/sauces'
      preLoaderRoute: typeof SaucesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CateringRoute: CateringRoute,
  ClubRoute: ClubRoute,
  FeedbackRoute: FeedbackRoute,
  GiftCardsRoute: GiftCardsRoute,
  MenuRoute: MenuRoute,
  NewsRoute: NewsRoute,
  SaucesRoute: SaucesRoute,
  StoryRoute: StoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
